INSERT INTO oban_jobs(
    args,
    attempt,
    attempted_at,
    attempted_by,
    cancelled_at,
    completed_at,
    discarded_at,
    errors,
    inserted_at,
    max_attempts,
    meta,
    priority,
    queue,
    scheduled_at,
    state,
    tags,
    worker
) VALUES (
    :args,
    :attempt,
    :attempted_at,
    :attempted_by,
    :cancelled_at,
    :completed_at,
    :discarded_at,
    :errors,
    coalesce(:inserted_at, timezone('UTC'::text, now())),
    :max_attempts,
    :meta,
    :priority,
    :queue,
    coalesce(:scheduled_at, timezone('UTC'::text, now())),
    :state,
    :tags,
    :worker
) RETURNING id, inserted_at, scheduled_at;
